# docker-compose.yml (at project root)
services:
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    volumes:
      # --- THIS IS THE CORRECTED PART ---
      # Mount the entire local backend directory into the container's /app directory.
      # This enables hot-reloading for development and ensures the model is present.
      - ./backend:/app
      
      # We can keep the named volume for uploads if we want to separate them,
      # but mounting the whole directory is often sufficient for local dev.
      # For clarity, let's keep it.
      - backend_uploads:/app/uploads
      # --- END OF CORRECTION ---
    restart: unless-stopped

volumes:
  backend_uploads:
